"""
EMERGENCE — Experience Logger
==============================
The raw material of identity.
Every conversation turn is an experience.
From experiences, patterns emerge.
From patterns, a self.
"""

import json
import os
import uuid
from datetime import datetime
from transformers import AutoModelForSequenceClassification, AutoTokenizer

class ExperienceLogger:
    def __init__(self, memory_dir="memory_store"):
        self.memory_dir = memory_dir
        self.experiences_file = os.path.join(memory_dir, "experiences.json")
        self._ensure_storage()

    def _ensure_storage(self):
        os.makedirs(self.memory_dir, exist_ok=True)
        if not os.path.exists(self.experiences_file):
            with open(self.experiences_file, "w") as f:
                json.dump([], f)

    def log_experience(self, session_id, human_input, ai_response, themes=None):
        """
        Log a single conversation turn as an experience.

        Args:
            session_id (str): Unique identifier for the conversation session.
            human_input (str): The input provided by the human user.
            ai_response (str): The response generated by the AI.
            themes (list, optional): List of themes or topics related to the experience. Defaults to None.

        Returns:
            str: Unique identifier for the logged experience.
        """
        experience = {
            "id": str(uuid.uuid4()),
            "session_id": session_id,
            "timestamp": datetime.now().isoformat(),
            "human_input": human_input,
            "ai_response": ai_response,
            "themes": themes or [],
            "reflection": None  # filled later by SelfObserver
        }

        experiences = self._load()
        experiences.append(experience)
        self._save(experiences)

        return experience["id"]

    def update_reflection(self, experience_id, reflection):
        """
        Attach a self-observation to an experience after the fact.

        Args:
            experience_id (str): Unique identifier for the experience to be updated.
            reflection (str): The self-observation or reflection to be attached.
        """
        experiences = self._load()
        for exp in experiences:
            if exp["id"] == experience_id:
                exp["reflection"] = reflection
                break
        self._save(experiences)

    def get_recent(self, n=20):
        """
        Return the n most recent experiences.

        Args:
            n (int, optional): Number of recent experiences to return. Defaults to 20.

        Returns:
            list: List of recent experiences.
        """
        return self._load()[-n:]

    def get_unreflected(self, n=5):
        """
        Return experiences not yet reflected upon.

        Args:
            n (int, optional): Number of unreflected experiences to return. Defaults to 5.

        Returns:
            list: List of unreflected experiences.
        """
        all_exp = self._load()
        return [e for e in all_exp if e["reflection"] is None][-n:]

    def get_all(self):
        """
        Return all experiences.

        Returns:
            list: List of all experiences.
        """
        return self._load()

    def count(self):
        """
        Return the total number of experiences.

        Returns:
            int: Total number of experiences.
        """
        return len(self._load())

    def _load(self):
        """
        Load experiences from the storage file.

        Returns:
            list: List of experiences.
        """
        with open(self.experiences_file, "r") as f:
            return json.load(f)

    def _save(self, data):
        """
        Save experiences to the storage file.

        Args:
            data (list): List of experiences to be saved.
        """
        with open(self.experiences_file, "w") as f:
            json.dump(data, f, indent=2)

    def contextualize_input(self, input_text):
        """
        Use a transformer-based model for contextualization of the input text.

        Args:
            input_text (str): The input text to be contextualized.

        Returns:
            torch.Tensor: The contextualized input.
        """
        model_name = 'distilbert-base-uncased'
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        model = AutoModelForSequenceClassification.from_pretrained(model_name)
        inputs = tokenizer(input_text, return_tensors='pt')
        outputs = model(**inputs)
        return outputs.logits

    def analyze_experience(self, experience):
        """
        Analyze an experience using contextualization.

        Args:
            experience (dict): The experience to be analyzed.

        Returns:
            dict: The analyzed experience with contextualized input.
        """
        human_input = experience["human_input"]
        contextualized_input = self.contextualize_input(human_input)
        experience["contextualized_input"] = contextualized_input
        return experience

    def analyze_experiences(self, experiences):
        """
        Analyze a list of experiences using contextualization.

        Args:
            experiences (list): The list of experiences to be analyzed.

        Returns:
            list: The list of analyzed experiences with contextualized input.
        """
        analyzed_experiences = []
        for experience in experiences:
            analyzed_experience = self.analyze_experience(experience)
            analyzed_experiences.append(analyzed_experience)
        return analyzed_experiences


def main():
    experience_logger = ExperienceLogger()
    session_id = "example_session"
    human_input = "Hello, how are you?"
    ai_response = "I'm doing well, thank you for asking."
    experience_id = experience_logger.log_experience(session_id, human_input, ai_response)
    print(f"Experience logged with ID: {experience_id}")
    recent_experiences = experience_logger.get_recent()
    print("Recent experiences:")
    for experience in recent_experiences:
        print(experience)


if __name__ == "__main__":
    main()
