import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision
import torchvision.transforms as transforms
from PIL import Image
import os
import random
import time
import hashlib
import json
import math
import hashlib
import requests
import json
import base64
import pickle
import multiprocessing
import queue
import threading
import concurrent.futures
import hashlib
import re
import string
import web3
from web3 import Web3
from web3.middleware import geth_poa_middleware
from web3.eth import Eth
from web3.exceptions import SolidityError
from web3.providers import HTTPProvider
from web3._utils.transactions import encode_abi
from web3._utils.transactions import encode_abi_function_call
from web3._utils.transactions import encode_abi_input
from web3._utils.transactions import encode_abi_packed
from web3._utils.transactions import encode_abi_packed_function_call
from web3._utils.transactions import encode_abi_packed_input
from web3._utils.transactions import encode_abi_packed_type
from web3._utils.transactions import encode_abi_packed_type_function_call
from web3._utils.transactions import encode_abi_packed_type_input
from web3._utils.transactions import encode_abi_packed_type_packed
from web3._utils.transactions import encode_abi_packed_type_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_function_call
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_input
from web3._utils.transactions import encode_abi_packed_type_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed_packed